### ISSUE TITLE
How do you use it ? No instructions ?????? in README 

### ISSUE THREAD

**Issue by developeralgo8888** [eaglx/VMPROTECT#1]
How do you use it ? No instructions ?????? in README

**Comment by eaglx** [comment]
Hi, thank you for your interest in my project. I'm currently working on the [0.2 version](https://github.com/eaglx/VMPROTECT/tree/dev), which will be more human friendly and will be released within a month or two. Then I will include a some manual.

**Comment by eaglx** [comment]
All necessary information in the [README.md](https://github.com/eaglx/VMPROTECT/blob/master/README.md).
